version: 2
updates:
  # Main monorepo package.json (pnpm/npm/yarn)
  - package-ecosystem: "npm"
    directory: "/tools/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
    assignees:
      - "Beginnerinvestorhub"
    reviewers:
      - "Beginnerinvestorhub"
    commit-message:
      prefix: "deps"
      include: "scope"
    rebase-strategy: "auto"
    versioning-strategy: "increase"

  # Web app package.json (Next.js frontend)
  - package-ecosystem: "npm"
    directory: "/tools/apps/web/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
    assignees:
      - "Beginnerinvestorhub"
    reviewers:
      - "Beginnerinvestorhub"
    commit-message:
      prefix: "deps"
      include: "scope"
    rebase-strategy: "auto"
    versioning-strategy: "increase"

  # Shared API types package.json
  - package-ecosystem: "npm"
    directory: "/tools/packages/api-types/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
    assignees:
      - "Beginnerinvestorhub"
    reviewers:
      - "Beginnerinvestorhub"
    commit-message:
      prefix: "deps"
      include: "scope"
    rebase-strategy: "auto"
    versioning-strategy: "increase"

  # Backend API Node.js/TypeScript Express app
  - package-ecosystem: "npm"
    directory: "/tools/services/backend-api/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
    assignees:
      - "Beginnerinvestorhub"
    reviewers:
      - "Beginnerinvestorhub"
    commit-message:
      prefix: "deps"
      include: "scope"
    rebase-strategy: "auto"
    versioning-strategy: "increase"

  # AI Behavioral Nudge Engine Python requirements
  - package-ecosystem: "pip"
    directory: "/tools/services/ai-behavioral-nudge-engine/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
    assignees:
      - "Beginnerinvestorhub"
    reviewers:
      - "Beginnerinvestorhub"
    commit-message:
      prefix: "deps"
      include: "scope"
    rebase-strategy: "auto"
    versioning-strategy: "increase"

  # Market Data Ingestion Python requirements
  - package-ecosystem: "pip"
    directory: "/tools/services/market-data-ingestion/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
    assignees:
      - "Beginnerinvestorhub"
    reviewers:
      - "Beginnerinvestorhub"
    commit-message:
      prefix: "deps"
      include: "scope"
    rebase-strategy: "auto"
    versioning-strategy: "increase"

  # GitHub Actions workflow updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
