databases:
  - name: investment_hub_db
    databaseName: investment_hub
    user: investment_hub_user
    plan: free

services:
  - type: web
    name: backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: investment_hub_db
          property: connectionString
      - key: REDIS_URL
        value: "your_redis_connection_string" # Placeholder
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://your-app.vercel.app
      - key: ALLOWED_ORIGINS
        value: https://your-app.vercel.app,http://localhost:3000
      - key: FIREBASE_PROJECT_ID
        value: your-project-id
      - key: FIREBASE_CLIENT_EMAIL
        value: your-service-account@project.iam.gserviceaccount.com
      - key: FIREBASE_PRIVATE_KEY
        value: "-----BEGIN PRIVATE KEY-----\nYour private key here\n-----END PRIVATE KEY-----"
      - key: STRIPE_SECRET_KEY
        value: sk_test_your_stripe_secret_key
      - key: STRIPE_WEBHOOK_SECRET
        generateValue: true
      - key: ALPHA_VANTAGE_API_KEY
        value: your_alpha_vantage_key
      - key: OPENAI_API_KEY
        value: your_openai_api_key
      - key: API_KEY_NUDGE_ENGINE
        generateValue: true
  - type: web
    name: python-engine
    env: docker
    dockerfilePath: ./python-engine/Dockerfile
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: investment_hub_db
          property: connectionString
      - key: REDIS_URL
        value: "your_redis_connection_string" # Placeholder
      - key: CORS_ORIGINS
        value: https://your-app.vercel.app,http://localhost:3000
      - key: OPENAI_API_KEY
        value: your_openai_api_key
      - key: ANTHROPIC_API_KEY
        value: your_anthropic_api_key
      - key: NUDGE_ENGINE_SECRET
        generateValue: true
      - key: ALPHA_VANTAGE_API_KEY
        value: your_alpha_vantage_key
      - key: FINANCIAL_MODELING_PREP_API_KEY
        value: your_fmp_key
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8000
      - key: DEBUG
        value: false
  - type: web
    name: ai-microservice
    env: docker
    dockerfilePath: ./ai_microservice/Dockerfile
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: investment_hub_db
          property: connectionString
      - key: PORT
        value: 8001
