# render.yaml
#
# This file is a Render Blueprint that defines the infrastructure for the
# Beginner Investor Hub backend. It has been updated to follow the standardized
# microservices architecture, ensuring each service is built from its own
# Dockerfile within the 'tools/' directory.

databases:
  - name: investment_hub_db
    databaseName: investment_hub
    user: investment_hub_user
    plan: free

redis:
  - name: bih-cache
    plan: free # Or your desired plan

services:
  # ----------------------------------------------------------------------
  # Main Backend API Gateway (Node.js)
  # ----------------------------------------------------------------------
  - type: web
    name: backend-api # Renamed for clarity and consistency
    env: docker
    # Corrected paths to point to the standardized location
    rootDir: ./tools/services/backend-api
    dockerfilePath: ./tools/services/backend-api/Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: investment_hub_db
          property: connectionString
      - key: REDIS_URL
        fromRedis:
          name: bih-cache
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      # Secrets are now managed in a centralized environment group
      - fromGroup: backend-secrets

  # ----------------------------------------------------------------------
  # AI Behavioral Nudge Engine (Python)
  # ----------------------------------------------------------------------
  - type: web
    name: ai-behavioral-nudge-engine
    env: docker
    rootDir: ./tools/services/ai-behavioral-nudge-engine
    dockerfilePath: ./tools/services/ai-behavioral-nudge-engine/Dockerfile
    healthCheckPath: /health
    envVars:
      - key: SERVICE_NAME
        value: ai-behavioral-nudge-engine
      - key: DATABASE_URL
        fromDatabase:
          name: investment_hub_db
          property: connectionString
      - key: REDIS_URL
        fromRedis:
          name: bih-cache
          property: connectionString
      - fromGroup: ai-secrets

  # ----------------------------------------------------------------------
  # Risk Calculation Engine (Python)
  # ----------------------------------------------------------------------
  - type: web
    name: risk-calculation-engine
    env: docker
    rootDir: ./tools/services/risk-calculation-engine
    dockerfilePath: ./tools/services/risk-calculation-engine/Dockerfile
    healthCheckPath: /health
    envVars:
      - key: SERVICE_NAME
        value: risk-calculation-engine
      - key: DATABASE_URL
        fromDatabase:
          name: investment_hub_db
          property: connectionString
      - key: REDIS_URL
        fromRedis:
          name: bih-cache
          property: connectionString

  # ----------------------------------------------------------------------
  # Market Data Ingestion Service (Python)
  # ----------------------------------------------------------------------
  - type: web
    name: market-data-ingestion
    env: docker
    rootDir: ./tools/services/market-data-ingestion
    dockerfilePath: ./tools/services/market-data-ingestion/Dockerfile
    healthCheckPath: /health
    envVars:
      - key: SERVICE_NAME
        value: market-data-ingestion
      - key: DATABASE_URL
        fromDatabase:
          name: investment_hub_db
          property: connectionString
      - key: REDIS_URL
        fromRedis:
          name: bih-cache
          property: connectionString
      - fromGroup: financial-api-keys

# Environment groups for managing secrets securely and centrally
envVarGroups:
  - name: backend-secrets
    envVars:
      - key: JWT_SECRET
        generateValue: true
  - name: ai-secrets
    envVars:
      - key: OPENAI_API_KEY
        sync: false
  - name: financial-api-keys
    envVars:
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
      - key: POLYGON_API_KEY
        sync: false
